name: Fetch

on:
  schedule:
    - cron: '5 */6 * * *'

  push:
    branches: [main]

  workflow_dispatch:

permissions:
  contents: write # for git push
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Fetch
        env:
          GH_TOKEN: ${{ secrets.PRIVATE_REPO_TOKEN }}
        run: |
          gh repo clone $(echo c3Rhc2FkZXYvaXB0di1hcmNoaXZl | base64 -d) temp-repo -- --depth 1
          mkdir -p _site
          cp temp-repo/streams.m3u8 _site
          cp temp-repo/epg.xml _site
          cp -r temp-repo/channels _site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
